export const sLocation = `GA	ADESA Atlanta	1
TX	ADESA Austin	1
AL	ADESA Birmingham	1
ID	ADESA Boise	1
MA	ADESA Boston	1
CA	ADESA Brashers	1
NY	ADESA Buffalo	1
NC	ADESA Charlotte	1
IL	ADESA Chicago	1
OH	ADESA Cincinnati/Dayton	1
OH	ADESA Cleveland	1
CO	ADESA Colorado Springs	1
MA	ADESA Concord	1
TX	ADESA Dallas	1
IA	ADESA Des Moines	1
TN	ADESA East Tennessee	1
ND	ADESA Fargo	1
MI	ADESA Flint	1
CA	ADESA Fresno	1
CA	ADESA Golden Gate	1
TX	ADESA Houston	1
IN	ADESA Indianapolis	1
FL	ADESA Jacksonville	1
MO	ADESA Kansas City	1
TN	ADESA Knoxville	1
MI	ADESA Lansing	1
NV	ADESA Las Vegas	1
KY	ADESA Lexington	1
AR	ADESA Little Rock	1
NY	ADESA Long Island	1
CA	ADESA Los Angeles	1
TN	ADESA Memphis	1
PA	ADESA Mercer	1
MN	ADESA Minneapolis	1
TN	ADESA Nashville	1
NJ	ADESA New Jersey	1
OR	ADESA Northwest	1
FL	ADESA Orlando	1
PA	ADESA PA	1
AZ	ADESA Phoenix	1
PA	ADESA Pittsburgh	1
OR	ADESA Portland	1
NC	ADESA Raleigh	1
NV	ADESA Reno	1
CA	ADESA Sacramento	1
UT	ADESA Salt Lake	1
TX	ADESA San Antonio	1
CA	ADESA San Diego	1
CA	ADESA San Jose	1
CA	ADESA San Jose UVA	1
FL	ADESA Sarasota	1
WA	ADESA Seattle	1
LA	ADESA Shreveport	1
SD	ADESA Sioux Falls	1
MO	ADESA St.Louis	1
NY	ADESA Syracuse	1
FL	ADESA Tampa	1
OK	ADESA Tulsa	1
VA	ADESA Washington DC	1
AB	ADESA Calgary	2
AB	ADESA Edmonton	2
NS	ADESA Halifax	2
ON	ADESA Kitchener	2
NB	ADESA Moncton	2
QC	ADESA Montreal	2
ON	ADESA Ottawa	2
QC	ADESA Quebec City	2
SK	ADESA Saskatoon	2
NL	ADESA St. John's	2
ON	ADESA Toronto	2
BC	ADESA Vancouver	2
ON	ADESA Windsor	2
MB	ADESA Winnipeg	2`;

export const sLocationSynonyms =  `INDY	ADESA Indianapolis	1
Cincinnati	ADESA Cincinnati/Dayton	1
Cincinati	ADESA Cincinnati/Dayton	1
Cincy	ADESA Cincinnati/Dayton	1
Dayton	ADESA Cincinnati/Dayton	1
DFW	ADESA Dallas	1
Sale Lake	ADESA Salt Lake city	1
`;

export const AdesaOffsite = `AK	1
AL	1
AR	1
AZ	1
CA	1
CO	1
CT	1
DE	1
FL	1
GA	1
HI	1
IA	1
ID	1
IL	1
IN	1
KS	1
KY	1
LA	1
MA	1
MD	1
ME	1
MI	1
MN	1
MO	1
MS	1
MT	1
NC	1
ND	1
NE	1
NH	1
NJ	1
NM	1
NV	1
NY	1
OH	1
OK	1
OR	1
PA	1
RI	1
SC	1
SD	1
TN	1
TX	1
UT	1
VA	1
VT	1
WA	1
WI	1
WV	1
WY	1
AB	2
BC	2
MB	2
NB	2
NL	2
NS	2
ON	2
QC	2
SK	2`;

export const certifiedPartner =
`OH - AKRON AUTO AUCTION
IL - AMERICA'S AUTO AUCTI...
SC - AMERICA'S AUTO AUCTI...
LA - AMERICA'S AUTO AUCTI...
MS - AMERICA'S AUTO AUCTI...
AL - AMERICA'S AUTO AUCTI...
GA - AMERICA'S AUTO AUCTI...
MS - AMERICA'S AUTO AUCTI...
TN - AMERICA'S AUTO AUCTI...
KY - AMERICA'S AUTO AUCTI...
TX - AMERICA'S AUTO AUCTI...
TX - AMERICA'S AUTO AUCTI...
GA - AMERICA'S AUTO AUCTI...
NC - AMERICA'S AUTO AUCTI...
FL - AMERICA'S AUTO AUCTI...
IL - AMERICA'S AUTO AUCTI...
MO - AMERICA'S AUTO AUCTI...
OH - AMERICA'S AUTO AUCTI...
CA - AUCTIONS IN MOTION -...
IL - BADGER STATE AUTO AU...
WI - BADGER STATE AUTO AU...
TX - BIG VALLEY AUTO AUCTION
WV - CAPITAL CITY AUTO AU...
CT - CENTRAL AUTO AUCTION
GA - CHARLESTON AUTO AUCTION
SC - CHARLESTON AUTO AUCTION
IN - CLARK COUNTY AUTO AU...
NY - CORRY AUTO DEALERS E...
OH - CORRY AUTO DEALERS E...
PA - CORRY AUTO DEALERS E...
TN - DEALERS AUTO AUCTION...
AL - DEALERS AUTO AUCTION...
TN - DEALERS AUTO AUCTION...
AL - DEALERS AUTO AUCTION...
MS - DEALERS AUTO AUCTION...
TN - DEALERS AUTO AUCTION...
OK - DEALERS AUTO AUCTION...
WA - DEALERS AUTO AUCTION...
WA - DEALERS AUTO AUCTION...
IA - DEALERS CHOICE AUTO ...
IL - DYER AUTO AUCTION, INC.
IN - DYER AUTO AUCTION, INC.
TX - EPI AUCTIONS LLC
MI - FASTLANE AUTO EXCHAN...
MI - GRAND RAPIDS AUTO AU...
PA - GREATER ERIE AUTO AU...
IN - GREATER KALAMAZOO AU...
MI - GREATER KALAMAZOO AU...
OH - GREATER KALAMAZOO AU...
IL - GREATER ROCKFORD AUT...
NC - GREENVILLE AUTO AUCT...
TX - HOUSTON AUTO AUCTION...
IN - INDIANA AUTO AUCTION
MO - KANSAS CITY INDEPEND...
KS - KC AUCTION DIRECT LLC
NM - LONE STAR AUTO AUCTI...
TX - LONE STAR AUTO AUCTI...
LA - LOUISIANA'S 1ST CHOI...
MA - LYNNWAY AUTO AUCTION
TN - MEMPHIS AUTO AUCTION
TX - METRO AUTO AUCTION D...
MO - MISSOURI AUTO AUCTION
IL - MORTON AUTO AUCTION INC
PA - NORTH EAST PENNSYLVA...
FL - ORLANDO LONGWOOD AUT...
VA - RICHMOND AUTO AUCTION
AL - SHOALS NORTH ALABAMA...
OH - SKIPCO AUTO AUCTION
GA - SOUTHEASTERN AUTO AU...
NC - SPEEDWAY AUTO AUCTIO...
NY - STATE LINE AUTO AUCTION
KS - SUNFLOWER AUTO AUCTION
MO - SUNFLOWER AUTO AUCTION
FL - TEXAS LONE STAR AUTO...
TX - TEXAS LONE STAR AUTO...
OH - VALUE AUTO AUCTION
VT - YORKMONT AUTO AUCTION
FL - YOUR AUCTION OF TAMP...
OK - Z66 AUTO AUCTION `;
